### ISSUE TITLE
provide the doc for convolutional.py 

### ISSUE THREAD

**Issue by larrycai** [InnoFang/what-digit-you-write#14]
It will be good to have related doc/ref for this python code (book or article?).

It will be extra good if `.ipynb` is provided

Thanks

Rgs, Larry

**Comment by InnoFang** [comment]
> It will be good to have related doc/ref for this python code (book or article?).
> 
> It will be extra good if `.ipynb` is provided
> 
> Thanks
> 
> Rgs, Larry

Actually, I do have a related reference for this python code, but it's a series of videos in simplified Chinese.

For the sake of respect for the author and sharing learning resources, I think I must attach a link: [人工智能实践：Tensorflow笔记](http://www.icourse163.org/course/PKU-1002536002). <br/> I also wrote a series of related `.ipynb` notes and the note related to the `convolutional.py` are [this](https://github.com/InnoFang/tensorflow2-from-zero/blob/master/11.%20Fashion%20MNIST.ipynb) and [this](https://github.com/InnoFang/tensorflow2-from-zero/blob/master/12.%20LeNet.ipynb).

But my notes are not enough for closing your issue, in order to really help you, I still think I should recommend some related  resources in English:
 + [TF Implementing LeNet-5 in TensorFlow 2.0](http://datahacker.rs/lenet-5-implementation-tensorflow-2-0/)
 + [LeNet-5 CNN with Keras](https://www.kaggle.com/curiousprogrammer/lenet-5-cnn-with-keras-99-48)

If you are a  beginner, TensorFlow docs may be more suitable for you:
 + [TensorFlow 2 quickstart for beginners](https://www.tensorflow.org/tutorials/quickstart/beginner)

Hope this reply can really help you.

**Comment by larrycai** [comment]
Good enough so far, thx.
